# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in ipgeobase.gemspec

gem 'rake', '~> 13.0'

gem 'minitest', '~> 5.0'
gem 'minitest-power_assert'

gem 'rubocop'

gem 'nokogiri-happymapper', require: 'happymapper'

gem 'webmock', require: 'webmock/minitest'

gem 'addressable'

gem 'simplecov', require: false, group: :test
